### PR TITLE
React migration

### PR DESCRIPTION
**Pull request by amarax**
@jlin95 I've migrated the existing code to React.js. Have a look at it, then I'll be merging this to master.

### CODE REVIEW

**Comment by jlin95** [comment]
It looks overall fine! 

Except that I thought you would use imports and exports. You MIGHT (this is just my 2 cents) want to consider an alternative folder structure like; 

components
    /Uploader
        /index.jsx
       /Uploader.jsx
      /uploader.css

for example ^. 

But I think the current structure works fine too!

**Comment by amarax** [comment]
I'm aware of splitting the CSS files for the specific components, but right now I'll just leave it as until I get to beautifying the app. I'll work on the data model first.

I also found out that import and export are not available on client-side JS without a build process. If you managed to get that to work let me know, and I'll update it.

I'll be merging and pushing a PR for a test framework next. Don't forget to migrate the repo to the CUTE organisation (I've invited you)!

**Comment by jlin95** [comment]
Nope, a bundler is still required, browser support is still pretty limited :( 

https://jakearchibald.com/2017/es-modules-in-browsers/ <-- they have just very very recently started to implement support for browsers

**Comment by jlin95** [comment]
Also just to be very clear, you want me to transfer ownership to the CUTE
Github organization and not just fork to the CUTE org right?

**Comment by amarax** [comment]
Yes that's absolutely correct, transfer ownership to CUTE.

**Pull request merged**
